name: Pool

on:
  push:
    paths:
      - .github/workflows/pool.yml # Only run a new workflow every time this file (pool.yaml) file changes
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: '0 8 * * *' # Run this workflow at 4 AM everyday

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: 
      # The first step is to check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2
      # The next step is a Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch poolers
        uses: githubocto/flat@v3
        with:
          http_url: https://dj15141xisgt0.cloudfront.net/json/poolers.json # 
          downloaded_filename: ./src/data/poolers.json
      - name: Fetch alignements 
        uses: githubocto/flat@v3
        with:
          http_url: https://dj15141xisgt0.cloudfront.net/json/alignements.json # 
          downloaded_filename: ./src/data/alignements.json
      - name: Fetch picks 
        uses: githubocto/flat@v3
        with:
          http_url: https://dj15141xisgt0.cloudfront.net/json/picks.json # 
          downloaded_filename: ./src/data/picks.json
      - name: Fetch joueurs 
        uses: githubocto/flat@v3
        with:
          http_url: https://dj15141xisgt0.cloudfront.net/json/joueurs.json # 
          downloaded_filename: ./src/data/joueurs.json
